#!/bin/bash
lock() {
    i3lock -c 000000
}
DISTRO=$(gawk -F= '/^NAME/{print substr($2, 2, length($2)-2)}' /etc/os-release)

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        if [ "$DISTRO" == "Ubuntu" ]
        then
            lock && dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Suspend" boolean:true
        elif [ "$DISTRO" == "Arch Linux" ]
        then
            lock && systemctl suspend
        fi
        ;;
    hibernate)
        if [ "$DISTRO" == "Ubuntu" ]
        then
            lock && dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Hibernate" boolean:true
        elif [ "$DISTRO" == "Arch Linux" ]
        then
            lock && systemctl hibernate
        fi
        ;;
    reboot)
        if [ "$DISTRO" == "Ubuntu" ]
        then
            dbus-send --system --print-reply --dest=org.freedesktop.login1 /org/freedesktop/login1 "org.freedesktop.login1.Manager.Reboot" boolean:true
        elif [ "$DISTRO" == "Arch Linux" ]
        then
            systemctl reboot
        fi
        ;;
    shutdown)
        if [ "$DISTRO" == "Ubuntu" ]
        then
            dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
        elif [ "$DISTRO" == "Arch Linux" ]
        then
            systemctl poweroff -i
        fi
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
