#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

bspc monitor -d I II III IV V VI VII VIII IX X


# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################
bspc config border_width         3
bspc config window_gap           15

bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "$MAGENTA"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

# monocle : one app and full-screen workflow 
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true



# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################
bspc rule -a kitty follow=on focus=on
bspc rule -a firefox desktop='^1'
bspc rule -a spotify desktop='^3'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# Set Background
nitrogen --restore &

# Set Cursor
xsetroot -cursor_name left_ptr

# Start sxhkd (Hotkey Deamon)
sxhkd &

# Start Polybar
$HOME/.config/polybar/launch.sh &

# Start dunst (Notification Manager)
dunst &

# Start picom composition
picom --config ~/.config/picom.conf & 

# setxkbmap gb

exec --no-startup-id  $HOME/.config/bspwm/scripts/xborder/xborders
